### ISSUE TITLE
Utf8Error trying to upload file

### ISSUE THREAD

**Issue by kulbinderdio** [purton-tech/fine-tuna#1] opened 2023-09-07 09:04 UTC
On MacMini (intel)

Error msg

fine-tuna-barricade-1     | [2023-09-07T08:47:13Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 822.209µs
fine-tuna-barricade-1     | [2023-09-07T08:47:13Z INFO  sqlx::query] SELECT id, user_id, session_verifier, …; rows affected: 0, rows returned: 1, elapsed: 1.085ms
fine-tuna-barricade-1     |     
fine-tuna-barricade-1     |     SELECT
fine-tuna-barricade-1     |       id,
fine-tuna-barricade-1     |       user_id,
fine-tuna-barricade-1     |       session_verifier,
fine-tuna-barricade-1     |       otp_code_confirmed,
fine-tuna-barricade-1     |       otp_code_encrypted,
fine-tuna-barricade-1     |       otp_code_attempts,
fine-tuna-barricade-1     |       otp_code_sent
fine-tuna-barricade-1     |     FROM
fine-tuna-barricade-1     |       sessions
fine-tuna-barricade-1     |     WHERE
fine-tuna-barricade-1     |       id = $1
fine-tuna-barricade-1     |     
fine-tuna-barricade-1     | [2023-09-07T08:47:13Z INFO  actix_web::middleware::logger] 172.18.0.3 "POST /app/team/1/dataset/1/doc_upload HTTP/1.1" 200 0 "-" "-" 0.003813
fine-tuna-barricade-1     | [2023-09-07T08:47:13Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 454.951µs
fine-tuna-app-1           | 2023-09-07T08:47:13.777191Z  INFO axum_server::documents::upload_doc: Sending document to unstructured
fine-tuna-unstructured-1  | 2023-09-07 08:47:13,831 unstructured_api DEBUG pipeline_api input params: {"request": "<starlette.requests.Request object at 0x7fb7a1891550>", "filename": "test-text.txt", "file_content_type": "text/plain", "response_type": "application/json", "m_coordinates": [], "m_encoding": [], "m_hi_res_model_name": [], "m_include_page_breaks": [], "m_ocr_languages": [], "m_pdf_infer_table_structure": [], "m_skip_infer_table_types": [], "m_strategy": [], "m_xml_keep_tags": []}
fine-tuna-unstructured-1  | 2023-09-07 08:47:13,852 unstructured_api DEBUG partition input data: {"content_type": "text/plain", "strategy": "auto", "ocr_languages": "eng", "coordinates": false, "pdf_infer_table_structure": false, "include_page_breaks": false, "encoding": null, "model_name": null, "xml_keep_tags": false, "skip_infer_table_types": ["pdf", "jpg", "png"]}
fine-tuna-unstructured-1  | 2023-09-07 08:47:17,821 172.18.0.6:52640 POST /general/v0/general HTTP/1.1 - 200 OK
fine-tuna-app-1           | 2023-09-07T08:47:17.827533Z  INFO axum_server::documents::upload_doc: Generating embeddings
fine-tuna-app-1           | thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 1022, error_len: None }', crates/axum-server/src/open_api.rs:51:10

[test-text.txt](https://github.com/purton-tech/fine-tuna/files/12546911/test-text.txt)

**Comment by ianpurton** [comment] 2023-09-07 09:10
@kulbinderdio Thanks, I was able to reproduce this.

**Comment by ianpurton** [comment] 2023-09-07 09:50
So there are 2 issues here. Rust was expecting UTF-8 so I fixed it so that it ignores non UTF characers.

Secondly there's a time out because it takes a long time to process the file.

The timeout could be with envoy or the axum server. I'll check this.

But going forward looks like we'll need a job to process files so that the user doesn't have to wait.

**Comment by ianpurton** [comment] 2023-09-07 10:18
Fixed in version 1.4.7

**Closed by ianpurton** 2023-09-07 10:18 UTC
